version: '3.2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db_100
      - POSTGRES_USER=test_user100
      - POSTGRES_PASSWORD=test_user100
 
    ports:
      - "5436:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

